Update assignment4.yml

diff --git a/.github/workflows/assignment4.yml b/.github/workflows/assignment4.yml
--- a/.github/workflows/assignment4.yml
+++ b/.github/workflows/assignment4.yml
@@ -129,7 +129,7 @@ jobs:
         # Debug check for log.txt existence and location
         echo "Checking for log.txt in workflow-artifacts:"
         find . -name log.txt
-        ls workflow-artifacts || echo "log.txt not found in workflow-artifacts"
+        ls -l workflow-artifacts || echo "log.txt not found in workflow-artifacts"
         
         if [ "$CONT_COUNT" -eq 3 ]; then
           echo "Container up and running" >> workflow-artifacts/log.txt
