Update assignment4.yml

diff --git a/.github/workflows/assignment4.yml b/.github/workflows/assignment4.yml
--- a/.github/workflows/assignment4.yml
+++ b/.github/workflows/assignment4.yml
@@ -110,9 +110,9 @@ jobs:
       run: |
         docker ps
         if [ "$(docker ps -q | wc -l)" -eq 3 ]; then
-          echo "Container up and running" >> log.txt
+          echo "Container up and running" >> workflow-artifacts/log.txt
         else
-          echo "Container failed to run" >> log.txt
+          echo "Container failed to run" >> workflow-artifacts/log.txt
           exit 1
         fi
 
@@ -135,7 +135,7 @@ jobs:
     - name: Run tests
       run: |
         cd tests
-        pytest -v assn4_test.py > assn4_test_results.txt || true
+        pytest -v assn4_tests.py > assn4_test_results.txt || true
 
     - name: tests results
       run: |
