Update assignment4.yml

diff --git a/.github/workflows/assignment4.yml b/.github/workflows/assignment4.yml
--- a/.github/workflows/assignment4.yml
+++ b/.github/workflows/assignment4.yml
@@ -141,12 +141,12 @@ jobs:
         # Debug check for log.txt existence and location
         echo "Checking for log.txt in workflow-artifacts:"
         find . -name log.txt
-        ls -l workflow-artifacts/log.txt || echo "log.txt not found in workflow-artifacts"
+        ls -l ./workflow-artifacts/home/runner/work/assn4/assn4/log.txt || echo "log.txt not found in workflow-artifacts"
         
         if [ "$CONT_COUNT" -eq 3 ]; then
-          echo "Container up and running" >> workflow-artifacts/log.txt
+          echo "Container up and running" >> ./workflow-artifacts/home/runner/work/assn4/assn4/log.txt/log.txt
         else
-          echo "Container failed to run" >> workflow-artifacts/log.txt
+          echo "Container failed to run" >> ./workflow-artifacts/home/runner/work/assn4/assn4/log.txt/log.txt
           exit 1
         fi
 
